project:
  type: website
  output-dir: docs
  resources:
    - "QISeminar25/slides.html"
    - "archived/**"

website:
  description: "Exploring reality, one model at a time."
  site-url: https://tanahy.github.io
  title: "This Is a Pipe"
  navbar:
    right:
      - slides.qmd
      - text: "CV"
        href: cv.qmd
      - about.qmd

format:
  html:
    theme:
      light: minty
      dark: superhero
    css: styles.css


